GET http://localhost:3001/todos


###
POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Kniebeugen 3x10"
}


###

DELETE http://localhost:3001/todo/delete/641c7a62ee0cb9a05b4954fc



###

PUT http://localhost:3001/todo/complete/641cbd80968db95534f379f0